### ISSUE TITLE
February Sprint Retrospective

### ISSUE THREAD

**Issue by Isaiahensley** [Isaiahensley/Aquatic-RIG#46]
### **Description:**

The objective of this issue is to create retrospective for February. Everyone will link their retrospective points with specific issue as well as specific person**(Important)** Be honest.

### **Requirements:**

Everyone should input:
1) What went well
2) What didn't go as planned 
3) Action items (things the group or member should do to improve on)

### **Expected Vs Actual Behavior:** 

- Fill up all the _What went well_, _What didn't go as planned_,  and _Action Items_. Everything mentioned should be honest and reflect each specific team members contributions to the project.

### **Issue Links:**

- **Make sure to put links to issues you talk about and describe where something went well or bad in that particular issue.**

### **For Issue Resolution:**

- Sudeep will present and go over each team members retrospective, so that our team is better prepared for March's sprint.

**Comment by Isaiahensley** [comment]
**January Retrospective**

**What Went Well:**
1) Consistent meetings the day before and an hour before class.
2) Team members have improved formatting issues.
     Examples:
    • Richard [Searching for NC File Datasets](https://github.com/Isaiahensley/Aquatic-RIG/issues/63)
    • Sudeep [Global Exception Handling and Error Logging](https://github.com/Isaiahensley/Aquatic-RIG/issues/64)
    • Maria [Homepage Summary Section](https://github.com/Isaiahensley/Aquatic-RIG/issues/61)
    • Isaiah [Heat Map Visualization](https://github.com/Isaiahensley/Aquatic-RIG/issues/56)
3) Standups have generally improved.
    • Standups accurately represent work done by team members.
    • Standups are reviewed before class
4) Group members are informed on work done by others. Communication has improved drastically.

**What Didn't Go As Planned:**
1) Giving descriptive titles to issues.
2) Completing issues on time. Dates have been pushed back on several issues this month. (Issues don't show original dates set so showing examples will have to be done verbally)
3) To have our website complete for our demo we need to complete issues quicker. We should already have most of of the website complete.

**Actions Needed:**
1) Make sure team members give accurate titles to created issues
2) Complete issues on time.
3) Complete more issues each week to prepare for our demo at the end of March.

**Comment by spaude11** [comment]
February Retrospective

**What Went Well:**
1. Most issues were being closed with in time limits. 
2. Every team member were putting effort into giving more descriptive issue format. 
3. Feedback page: Richard did really well for completing the issue on time. 
4.. Dataset management page: Isaiah is working really hard for the main part of our website, He is improving the 


**What Didn't Go As Planned:**
1. Workflow UI: Waiting for everyone's file in github repository as well as different workflows is rendering my time. 
2. February Sprint: The website development needed more actions to be completed within this month for march's presentation
3. Communication: Issues were based on the work division but sometime due to miscommunication between the team the issue naming as well as task division was mismatched. 

What needs to be done: 
1. I will work on working with workflows. 
2. More issue generation based on works needs to be done
3. Having proper communication before stand ups  
4. More description in github issue is needed. 
5. 

**Actions Needed:**
1. Work with the template for issues description 
2. Finalize our mockup website
3. Pull everyone's code  and merge in develop branch for tests. 
4. Create march's sprints for final product

**Comment by rpeters47** [comment]
What went well
What could've been better
Improve on
Will edit this later

**Comment by blackm61** [comment]
### Maria Black Retrospective

### **What went well:**

1. I was able to complete work on time and completed within the scheduled due dates.
Examples:
#52 -- _note due dates_

2. Team Members and I have been formatting issues correctly based on the templates we've created: 
#65

3. I've begun work on finalizing changes to our home page with the issue: #61 , upon completion and review, I will be able to merge this branch to our repository.   

4. Stand-ups have improved thanks to the group reviewing each team member's stand-up before class.
• Our standups accurately represent work done by team members.
• Our standups are reviewed before class

### **What could've been better:**

1.  **Issue-Completion**: my issues were not always completed by their respective due dates.

Example:
#52  -- due date had to be moved, but issue was completed
#61 -- due date has to be moved, and is currently incomplete


3. Our sprint planning from January did not allow us to best plan out what we would work on for this month.

### **Improve on:**

- [ ] - I need to improve on completing my issues by the **correct due date**, or also consider having more **accurate due dates and timelines** while creating our future sprints
