### ISSUE TITLE
Optimizing User Feedback Questionnaire

### ISSUE THREAD

**Issue by rpeters47** [Isaiahensley/Aquatic-RIG#57]
This issue is for creating meaningful questions to ask in our website's feedback section and implementing them.

**Comment by rpeters47** [comment]
Overall Satisfaction Rating: Add a rating scale (e.g., 1 to 5 stars) where users can rate their overall satisfaction with the website.

Specific Feedback Fields:

1. Ease of Use: Ask users to rate how easy it was to navigate the website and interact with the data visualization tools.
2. Design and Layout: Gather feedback on the website's design, aesthetics, and organization.
3. Performance: Inquire about the website's loading speed, responsiveness, and any technical issues users may have encountered.
4. Data Visualization Quality: Assess users' opinions on the effectiveness and clarity of the NC files data visualization.
5. Features and Functionality: Allow users to comment on specific features they found useful or lacking.
6. Suggestions for Improvement: Provide an open-ended field where users can share any suggestions or ideas for enhancing the website.
7. User Demographics: Optionally, include demographic questions such as age range, occupation, or industry to better understand your website's user base.
8. User Experience: Include questions or fields where users can describe their experience using the website in their own words. This can provide valuable insights into usability issues or positive aspects of the website.
9. Contact Information (Optional): Offer users the option to provide their email address or contact information if they would like a response or follow-up regarding their feedback.
10. Privacy and Data Usage: Include a brief statement about how you will use the feedback data and ensure users that their responses will be kept confidential and used only for improving the website.

**Comment by spaude11** [comment]
Looks good, we can work on providing more familiar experience as well some way to contact us directly in case they want us to approach.

**Comment by rpeters47** [comment]
![Screenshot 2024-02-13 230922](https://github.com/Isaiahensley/Aquatic-RIG/assets/143751338/ff849207-3a89-4450-a1d1-04ea24f9ec7d)
Specific Feedback Fields added.

**Comment by spaude11** [comment]
Looks good but I need your issue to be formatted like this. 
To enhance the clarity and productivity of our standups, I require that all issues presented adhere to a detailed format, as exemplified below. This approach will not only improve our understanding of each issue but also streamline our collaborative efforts to address them.

Sample Format for Issue Presentation:

Description: Clearly state the problem, including any specific error messages or unexpected behavior. Detail the context in which the issue occurs.

Steps to Reproduce: Provide a step-by-step guide on how to encounter the issue, making it easier for team members to replicate and understand the problem.

Expected vs. Actual Behavior: Describe what the expected behavior should be and how the actual outcome deviates from this expectation.

Code Snippets: Include relevant code snippets or configurations that relate to the issue, aiding in a more technical understanding and discussion.

Environment Details: Mention the operating system, software versions, and any other environment specifics that could influence the issue.

For Issue Resolution:

Detail the investigation, proposed changes, and the outcome, ensuring to describe how the resolution addresses the issue. Include modified code snippets and a summary of the impact of these changes.


If you didn't encounter any problem while coding then post overall goal instead of errors. and how you acheive it. Issue is not only for errors but can be made for development too.

**Comment by spaude11** [comment]
Looks really good.
