### ISSUE TITLE
Template

### ISSUE THREAD

**Issue by spaude11** [Isaiahensley/Aquatic-RIG#65]
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by Isaiahensley** [comment]
@spaude11 I made some templates for our issues. You messaged me earlier and told me It wouldn't let you create them since I'm the github repository owner.

There are two options now when creating an issue:

### **Bug**

Bug Description
A clear and concise description of what the bug is.

To Reproduce
Steps to reproduce the behavior:

Go to '...'
Click on '....'
Scroll down to '....'
See error
Expected vs Actual behavior
A clear and concise description of what you expected to happen.

Screenshots
If applicable, add screenshots to help explain your problem.

Code Snippet
If applicable, add code to help explain your problem.

Desktop (please complete the following information):

OS: [e.g. iOS, Windows 10]
Browser: [e.g. chrome, safari]
IDE: [e.g. pycharm, visual studio]
Language: [e.g. python 3]
Additional context
Add any other context about the problem here.


### **Feature**
Description:
A clear and concise description of the feature you are making this issue for.

Expected Outcome:
A clear and concise description of the expected outcome.

Solution:
A clear and concise description of how you will achieve the desired outcome.

Additional context
Add any other information here such as example screenshots, existing code, or links to sources that will be used to solve this issue.

**Comment by Isaiahensley** [comment]
Additionally, I believe it will automatically assign the issue to whoever creates it. It will also give that issue a label. **Bug** for a bug, or **Enhancement** for a new feature.

**Comment by spaude11** [comment]
Looks good. Thank you

**Comment by spaude11** [comment]
I am closing the issue
